server:
  host: 0.0.0.0
  port: 8080
  timeout:
    server: "30s"
    read: "15s"
    write: "10s"
    idle: "5s"
redis:
  addr: localhost:6379
  password: ""
  db: 0
  keys:
    - wv_high_spammy_tlds
logging:
  prefix: "redis2http "
  flag: 19